### ISSUE TITLE
Updating the app once its deployed

### ISSUE THREAD

**Issue by danshapiro** [WongSaang/chatgpt-ui#148]
Once the service is deployed with https://raw.githubusercontent.com/WongSaang/chatgpt-ui/main/deployment.sh, how do you recommend updating it? If I re-run the script, it removes all settings, messages, etc.

**Comment by WongSaang** [comment]
Hello, thank you for your feedback. 

If you want to persist data, you need to connect to an external database. I have updated the script so that if you run it again now, it will ask you if you want to connect to a database. Once you provide your database URL, you can achieve data persistence. 

The format of the database URL, please refer to this section of the documentation: https://wongsaang.github.io/chatgpt-ui/guide/configuration.html#database

You just need to re-run the command every time you want to update.

**Comment by danshapiro** [comment]
Thank you, this is very helpful!
