### ISSUE TITLE
能否配置chatgpt api的proxy

### ISSUE THREAD

**Issue by xiongbb** [WongSaang/chatgpt-ui#74]
原因你懂的

**Comment by DanielStones** [comment]
openai-python 使用的是request做请求，魔改一下就能实现了

**Comment by WongSaang** [comment]
[image: image.png]
有环境变量的，哥哥们

**Comment by WongSaang** [comment]
![image](https://user-images.githubusercontent.com/46235412/227706511-eae7acf1-04af-427b-81ab-bb144ec67503.png)

**Comment by chenweilie** [comment]
Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16344263e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

 默认的环境变量里面没有OPEN_API_PROXY，手动添加后，执行出来 是这个效果。
估计是后来的代码变了，不知道在哪里调整

**Comment by chenweilie** [comment]
> Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f16344263e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
> 
> 默认的环境变量里面没有OPEN_API_PROXY，手动添加后，执行出来 是这个效果。 估计是后来的代码变了，不知道在哪里调整

是我重新安装后覆盖了配置，但到目前为止还没有架设成功。用自己的接口，别的平台已经可以了。

**Comment by WongSaang** [comment]
格式：
`OPENAI_API_PROXY=https://proxy.openai.com/v1`

注意后面的 `v1`

**Comment by billy1991830** [comment]
OPENAI_API_PROXY 没有用, 
实测要用 HTTP_PROXY 和 HTTPS_PROXY
还要用NO_PROXY 避免本地也被代理
